# Generated by Django 3.1.3 on 2021-06-26 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='gender',
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='mobile',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('company', models.CharField(max_length=50, null=True)),
                ('user_type', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
