# Generated by Django 3.1.3 on 2021-06-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_auto_20210626_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
