# Generated by Django 3.1.3 on 2021-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_auto_20210626_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
