# Generated by Django 3.1.3 on 2021-08-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0005_auto_20210813_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(default='images/mickeymouse.png', null=True, upload_to='media/'),
        ),
    ]
