# Generated by Django 3.1.3 on 2021-08-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0008_auto_20210814_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='image',
            field=models.ImageField(null=True, upload_to='MEDIA_ROOT/images/'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(null=True, upload_to='MEDIA_ROOT/images/'),
        ),
    ]
