# Generated by Django 3.1.3 on 2021-09-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0011_auto_20210814_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='image',
        ),
    ]
