# Generated by Django 3.1.3 on 2021-10-09 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobportal', '0013_studentuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('skillset', models.CharField(max_length=50, null=True)),
                ('salary', models.FloatField(max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(max_length=250, null=True)),
                ('recuiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
