# Generated by Django 3.1.3 on 2021-10-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0014_jobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='skillset',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
