# Generated by Django 3.1.3 on 2021-10-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0015_auto_20211009_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='start_date',
            new_name='joining_date',
        ),
    ]
