# Generated by Django 3.1.3 on 2021-10-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0016_auto_20211009_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
