# Generated by Django 3.1.3 on 2021-10-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0017_auto_20211009_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='joining_date',
        ),
    ]
