# Generated by Django 3.1.3 on 2021-10-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0018_remove_jobmodel_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
