# Generated by Django 3.1.3 on 2021-10-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0020_auto_20211009_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.recruiter'),
        ),
    ]
