# Generated by Django 3.1.3 on 2021-10-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0021_auto_20211009_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='job_creation_date',
            field=models.DateField(null=True),
        ),
    ]
