# Generated by Django 3.1.3 on 2021-10-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0024_applications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
