# Generated by Django 3.1.3 on 2021-10-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0025_auto_20211016_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='recruiter',
        ),
    ]
