# Generated by Django 3.1.3 on 2021-10-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0028_newsletter_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter_sub',
            old_name='email',
            new_name='receipent',
        ),
    ]
