# Generated by Django 3.1.3 on 2021-10-17 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0029_auto_20211017_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='job_description_file',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
        ),
    ]
